import ProductCard from "../../ProductCard/ProductCard";

export default function AllProducts() {
  const products = [
    {
      name: "EVO 150 R",
      brand: "EVO",
      model: "150R-2025",
      category: "Motorcycle",
      price: 1500,
      stock: 25,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Sporty motorcycle with advanced features.",
    },
    {
      name: "EVO 200 X",
      brand: "EVO",
      model: "200X-2025",
      category: "Motorcycle",
      price: 1800,
      stock: 15,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Powerful 200cc motorcycle with great speed.",
    },
    {
      name: "EVO Electric",
      brand: "EVO",
      model: "Electric-2025",
      category: "Motorcycle",
      price: 1200,
      stock: 30,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Eco-friendly electric motorcycle for city commuting.",
    },
    {
      name: "Speedster 300",
      brand: "Speedster",
      model: "300-2025",
      category: "Motorcycle",
      price: 2200,
      stock: 10,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Racing-style motorcycle designed for high performance.",
    },
    {
      name: "Sport Cruiser",
      brand: "Speedster",
      model: "Cruiser-2025",
      category: "Motorcycle",
      price: 2000,
      stock: 20,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Comfortable and stylish cruiser for long rides.",
    },
    {
      name: "SuperFast GT",
      brand: "SuperFast",
      model: "GT-2025",
      category: "Bicycle",
      price: 550,
      stock: 50,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "High-speed bicycle for the performance enthusiast.",
    },
    {
      name: "Mountain King",
      brand: "MountainMaster",
      model: "MK-2025",
      category: "Bicycle",
      price: 700,
      stock: 18,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Durable mountain bike for tough trails.",
    },
    {
      name: "Urban Rider",
      brand: "UrbanCycle",
      model: "Rider-2025",
      category: "Bicycle",
      price: 400,
      stock: 40,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Perfect bicycle for daily commuting.",
    },
    {
      name: "CrossFit Pro",
      brand: "FitGear",
      model: "Pro-2025",
      category: "Fitness Equipment",
      price: 250,
      stock: 35,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Durable fitness equipment for intense workout routines.",
    },
    {
      name: "FlexPro 300",
      brand: "FlexGym",
      model: "300-2025",
      category: "Fitness Equipment",
      price: 180,
      stock: 50,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Versatile fitness equipment for home gyms.",
    },
    {
      name: "StrengthMaster",
      brand: "PowerGym",
      model: "Master-2025",
      category: "Fitness Equipment",
      price: 220,
      stock: 25,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Strength training equipment with multi-functionality.",
    },
    {
      name: "EcoFresh Blender",
      brand: "EcoHome",
      model: "Blender-2025",
      category: "Home Appliances",
      price: 100,
      stock: 50,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Eco-friendly blender for smooth and fresh smoothies.",
    },
    {
      name: "Smart Coffee Maker",
      brand: "SmartHome",
      model: "CoffeeMaker-2025",
      category: "Home Appliances",
      price: 120,
      stock: 30,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Smart coffee maker with programmable features.",
    },
    {
      name: "UltraCook Oven",
      brand: "UltraHome",
      model: "Oven-2025",
      category: "Home Appliances",
      price: 300,
      stock: 15,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "High-performance oven for quick cooking.",
    },
    {
      name: "CushionPro Sofa",
      brand: "HomeComfort",
      model: "Sofa-2025",
      category: "Furniture",
      price: 500,
      stock: 20,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Comfortable and stylish sofa for modern homes.",
    },
    {
      name: "ModernDesk 2025",
      brand: "HomeTech",
      model: "Desk-2025",
      category: "Furniture",
      price: 220,
      stock: 30,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Sleek, modern desk for home offices.",
    },
    {
      name: "Classic Bookshelf",
      brand: "ClassicFurniture",
      model: "Shelf-2025",
      category: "Furniture",
      price: 150,
      stock: 45,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Timeless wooden bookshelf for your living room.",
    },
    {
      name: "Vortex Mixer",
      brand: "VortexTech",
      model: "Mixer-2025",
      category: "Kitchen Appliances",
      price: 150,
      stock: 40,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "High-performance mixer for smooth blending.",
    },
    {
      name: "GrillMaster Pro",
      brand: "GrillTech",
      model: "Pro-2025",
      category: "Kitchen Appliances",
      price: 250,
      stock: 20,
      image: "https://i.ibb.co.com/8gFCpXkM/EVO-150-R-1615829353624.jpg",
      description: "Powerful grill for all your outdoor cooking needs.",
    },
  ];

  return (
    <div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
        {products.map((product) => (
          <ProductCard product={product} />
        ))}
      </div>
    </div>
  );
}
